### ISSUE TITLE
something wrong about  the training result

### ISSUE THREAD

**Issue by DavidKong96** [ximinng/LLM4SVG#14]
hi, i try to reproduce your result in Qwen-2.5-VL-7B, but i got this result below in 14000 training steps

![Image](https://github.com/user-attachments/assets/1049d547-b573-4cee-ace1-7233857b7420)

could you please let me konw where i did wrong?

I pulled the latest repository, and below is the traning config i use.
```yaml
### model
model_name_or_path: ../weights/Qwen2.5-VL-7B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 128
lora_target: all
#lora_dropout: 0.1

### dataset
dataset: SVGX_SFT_vision_25k_int_enc
template: qwen2_vl
cutoff_len: 4096
max_samples: 20000000
overwrite_cache: true
preprocessing_num_workers: 128

### output
output_dir: saves/encode-code/qwen2_5vl-7B-lora-sft
logging_steps: 50
save_steps: 2000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 3.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### new tokens
new_special_tokens_config: data/SVGX-dataset/svg_tokens.yaml
init_special_tokens: semantic_init

### generation
max_length: 4096
max_new_tokens: 4096

### eval
val_size: 0.02
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 2000
```
``
thank you.
